---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowmanager
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: flowmanager
      containers:
        - image: axway/flowmanager:[FLOWMANAGER_VERSION]
          name: flowmanager
          env:
            - name: ACCEPT_EULA
              value: ""
            - name: FM_GENERAL_LOGGING_LEVEL
              value: "INFO"
            - name: FM_LOGS_CONSOLE
              value: "yes"
            - name: FM_GENERAL_FQDN
              value: "localhost"
            - name: FM_GENERAL_UI_PORT
              value: "443"
            - name: FM_DATABASE_HOST
              value: "flowmanager-mongodb.<NAMESPACE>.svc.cluster.local:27017"
            - name: FM_DATABASE_NAME
              value: "umcft"
            - name: FM_DATABASE_USE_SSL
              value: "false"
            - name: FM_HTTPS_USE_CUSTOM_CERT
              value: "no"
            - name: FM_HTTPS_KEYSTORE
              value: /opt/axway/FlowManager/configs/uicert.pem
            - name: FM_GOVERNANCE_CA_FILE
              value: /opt/axway/FlowManager/configs/governanceca.pem
            - name: FM_CFT_SHARED_SECRET
              value: ""
            - name: FM_CFT_UPDATES_PATH
              value: "/opt/axway/FlowManager/updates/cft/"
            - name: FM_JVM_XMN
              value: "768M"
            - name: FM_JVM_XMS
              value: "2G"
            - name: FM_JVM_XMX
              value: "4G"
---
apiVersion: v1
kind: Secret
metadata:
  name: flowmanager-env
  labels:
    app: flowmanager
type: Opaque
data:
  FM_GENERAL_ENCRYPTION_KEY: ""
  FM_HTTPS_KEYSTORE_PASSWORD: ""
  FM_CFT_SHARED_SECRET: ""
  FM_DATABASE_USER_NAME: ""
  FM_DATABASE_USER_PASSWORD: ""
  FM_GOVERNANCE_CA_PASSWORD: ""          