##
## Flow Manager Core deployment
##
core:
  replicaCount: 2

  ## Docker image used for the customer
  image:
    repository: axway/flowmanager
    tag: 2.0.200709

  ## Environment variables
  envFromValueDisabled: true
  envFromConfigMapRefDisabled: true
  envFromSecretKeyRefDisabled: true
      
    
  ## Volumes
  volumesSecretDisabled: false
  volumesMountsSecretDisabled: false
  
  ## Resources specification
  resources:
    requests:
      cpu: "2000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "4Gi"
  ## Service
  service:
    type: ClusterIP # or LoadBalancer
    annotations: {}
    externalPort: 8081
  ##
  ## Security parameters
  ##
  serviceAccount:
    create: false
    # name: ~

  rbac:
    create: false

  pspEnable: false

  podAnnotations: {}


  containerSecurityContext:
    {}


  ## Configure readiness and liveness for health check
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /fm/login
      port: 8081
      scheme: HTTP
    initialDelaySeconds: 100
    periodSeconds: 5
    successThreshold: 3

  livenessProbe:
    httpGet:
      path: /api/v2/internals/stability
      port: 8081
      scheme: HTTP
    initialDelaySeconds: 100
    successThreshold: 1
    failureThreshold: 2
    periodSeconds: 10

  ## Setup ingress for Flow Manager Core
  ingress:
    enabled: false                