apiVersion: v1  
kind: Secret  
metadata:  
  name: mongodb-secret-files  
type: Opaque  
data:  
  governanceca-p12: <governanceca-p12-base64>
  mongodb-ca-cert: <mongodb-ca-cert-base64>
  mongodb-ca-key: <mongodb-ca-key-base64>  
  mongodb-client-pem: ""