---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowmanager
  labels:
    app: flowmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowmanager
  template:
    metadata:
      labels:
        app: flowmanager
    spec:
      serviceAccountName: flowmanager
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: flowmanager
          image: ""
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: flowmanager-env
          volumeMounts:
            - name: license
              readOnly: true
              mountPath: /opt/axway/FlowManager/conf/license/license.xml
              subPath: license.xml
            - name: uicert
              readOnly: true
              mountPath: /opt/axway/FlowManager/configs/uicert.pem
              subPath: uicert.pem
            - name: governance
              readOnly: true
              mountPath: /opt/axway/FlowManager/configs/governanceca.pem
              subPath: governanceca.pem
            - name: public-key-st
              readOnly: true
              mountPath: /opt/axway/FlowManager/st-fm-plugin/public-key
              subPath: public-key
            - name: st-fm-plugin-ca
              readOnly: true
              mountPath: /opt/axway/FlowManager/st-fm-plugin/st-fm-plugin-ca.pem
              subPath: st-fm-plugin-ca.pem
            - name: init-template
              readOnly: true
              mountPath: /opt/axway/FlowManager/init/initialize_template.json
              subPath: initialize_template.json
          ports:
            - name: fm-https
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/v2/internals/stability
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /fm/login
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 100
            periodSeconds: 5
            successThreshold: 3
      volumes:
        - name: license
          secret:
            secretName: license
            defaultMode: 420
        - name: uicert
          secret:
            secretName: uicert
            defaultMode: 420
        - name: governance
          secret:
            secretName: governanceca
            defaultMode: 420
        - name: st-fm-plugin-ca
          secret:
            secretName: st-fm-plugin-ca
            defaultMode: 420
        - name: public-key-st
          secret:
            secretName: public-key-st
            defaultMode: 420
        - name: init-template
          projected:
            sources:
            - configMap:
                name: st-init-template