---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-plugin
  labels:
    app: flowmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowmanager
  template:
    metadata:
      labels:
        app: flowmanager
    spec:
      serviceAccountName: flowmanager
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: st-plugin
          image: ""
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: license
              readOnly: true
              mountPath: /opt/axway/FlowManager/conf/license/license.xml
              subPath: license.xml
            - name: governance
              readOnly: true
              mountPath: /opt/axway/FlowManager/configs/governanceca.p12
              subPath: governanceca.p12
          ports:
            - name: fm-https
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/v2/internals/stability
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /fm/login
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 100
            periodSeconds: 5
            successThreshold: 3
      volumes:
        - name: license
          secret:
            secretName: flowmanager-license
            defaultMode: 420
        - name: uicert
          secret:
            secretName: flowmanager-uicert
            defaultMode: 420
        - name: governance
          secret:
            secretName: flowmanager-governance
            defaultMode: 420
