---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: st-plugin
  labels:
    app: flowmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowmanager
  template:
    metadata:
      labels:
        app: flowmanager
    spec:
      serviceAccountName: flowmanager
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: st-plugin
          image: ""
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: st-env
          env:
            - name: ST_FM_PLUGIN_HOST
              value: "localhost"    
          volumeMounts:
            - name: st-fm-plugin-shared-secret
              readOnly: true
              mountPath: /usr/src/app/src/st-fm-plugin-shared-secret
              subPath: st-fm-plugin-shared-secret
            - name: governance
              readOnly: true
              mountPath: /usr/src/app/src/governanceca.pem
              subPath: governanceca.pem
            - name: st-fm-plugin-cert-key
              readOnly: true
              mountPath: /usr/src/app/src/st-fm-plugin-cert-key.pem
              subPath: st-fm-plugin-cert-key.pem
            - name: st-fm-plugin-cert
              readOnly: true
              mountPath: /usr/src/app/src/st-fm-plugin-cert.pem
              subPath: st-fm-plugin-cert.pem
            - name: st-fm-plugin-ca
              readOnly: true
              mountPath: /usr/src/app/src/st-fm-plugin-ca.pem
              subPath: st-fm-plugin-ca.pem
            - name: private-key-st
              readOnly: true
              mountPath: /usr/src/app/src/private-key
              subPath: private-key
          ports:
            - name: st-plugin-http
              containerPort: 8899
              protocol: TCP
      volumes:
        - name: st-fm-plugin-shared-secret
          secret:
            secretName: st-fm-plugin-shared-secret
            defaultMode: 420
        - name: governance
          secret:
            secretName: governanceca
            defaultMode: 420
        - name: st-fm-plugin-cert-key
          secret:
            secretName: st-fm-plugin-cert-key
            defaultMode: 420
        - name: st-fm-plugin-cert
          secret:
            secretName: st-fm-plugin-cert
            defaultMode: 420
        - name: st-fm-plugin-ca
          secret:
            secretName: st-fm-plugin-ca
            defaultMode: 420
        - name: private-key-st
          secret:
            secretName: private-key-st
            defaultMode: 420