apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yml
  - psp.yml
  - role.yml
  - secret-env.yml
  - secret-env-st.yml
  - deployment.yml
  - service.yml
  - deployment-st.yml
  - service-st.yml
  - config-map-st.yaml
