---
apiVersion: v1
kind: Service
metadata:
  name: st-plugin
  labels:
    app: flowmanager
spec:
  ports:
    - name: st-plugin-http
      port: 8899
      protocol: TCP
  type: "NodePort"
  selector:
    app: flowmanager