apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.fullname" . }}-init-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "config.name" . }}
    chart: {{ include "config.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
data:
  initialize_template.json: |-
    {
      "objectsToCreate": [
        {
          "type": "ProductPlugin",
          "object": {
            "name": "SecureTransport",
            "description": "Manage flows definition for SecureTransport product.",
            "shortName": "ST",
            "pluginConnection": {
              "url": "https://{{ .Values.env.variables.FM_ST_PLUGIN_FQDN }}/api/v1",
              "pluginCertificate": "<plugin_ca>"
            },
            "pluginSSHKey": "<public_key>"
          }
        }
      ]
    }