apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flowmanager
  name: flowmanager_pod
spec:
  containers:
    - image: mongo:5.0
      name: mongodb
      args:
        - '-f'
        - '/opt/mongod.conf'
      ports:
        - name: mongoport
          hostPort: 27017
          containerPort: 27017
          protocol: tcp
      env:
        - name: MONGO_INTERNAL_PORT
          value: "27017"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: ""
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: ""
        - name: MONGO_APP_DATABASE
          value: "umcft"
        - name: MONGO_APP_USER
          value: ""
        - name: MONGO_APP_PASS
          value: ""
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: scripts
        - mountPath: /opt
          name: config
        - mountPath: /data/db
          name: data

    - image: docker.repository.axway.com/flowmanager-docker-prod/2.0/flowmanager_release:2.0.20230728
      name: flowmanager
      ports:
        - name: fmport
          hostPort: 8081
          containerPort: 8081
          protocol: tcp
      env:
        - name: ACCEPT_EULA
          value: ""
        - name: FM_GENERAL_FQDN     # FQDN of the machine
          value: ""
        - name: FM_GENERAL_UI_PORT
          value: "8081"
        - name: FM_GENERAL_ENCRYPTION_KEY
          value: ""
        - name: FM_HTTPS_USE_CUSTOM_CERT
          value: "false"
        - name: FM_HTTPS_KEYSTORE
          value: "/opt/axway/FlowManager/configs/uicert.pem"
        - name: FM_HTTPS_KEYSTORE_PASSWORD
          value: ""
        - name: FM_LOGS_CONSOLE
          value: "true"
        - name: FM_GENERAL_LOGGING_LEVEL
          value: "INFO"
        - name: FM_GOVERNANCE_CA_FILE
          value: "/opt/axway/FlowManager/configs/governanceca.pem"
        - name: FM_GOVERNANCE_CA_PASSWORD
          value: ""
        - name: FM_DATABASE_ENDPOINTS
          value: "flowmanager_pod-mongodb:27017"
        - name: FM_DATABASE_USER_NAME
          value: ""
        - name: FM_DATABASE_USER_PASSWORD
          value: ""
        - name: FM_DATABASE_NAME
          value: "umcft"
        - name: FM_DATABASE_USE_SSL
          value: "false"
        - name: FM_DATABASE_CERTIFICATES
          value: ""
        - name: FM_CFT_UPDATES_PATH
          value: "/opt/axway/FlowManager/updates/cft/"
        - name: FM_ST_PLUGIN_HOST
          value: "flowmanager_pod-st-fm-plugin"
        - name: FM_ST_PLUGIN_PORT
          value: "8899"
        - name: FM_ST_PLUGIN_CA_FILE
          value: "/opt/axway/FlowManager/st-fm-plugin/st-fm-plugin-ca.pem"
        - name: FM_ST_PLUGIN_PUBLIC_KEY
          value: "/opt/axway/FlowManager/st-fm-plugin/st-fm-plugin-public-key.pem"
        - name: FM_MONITORING_PLUGIN_HOST
          value: "flowmanager_pod-monitoring-fm-plugin"
        - name: FM_MONITORING_PLUGIN_PORT
          value: "3000"
        - name: FM_MONITORING_PLUGIN_CA_FILE
          value: "/opt/axway/FlowManager/monitoring-fm-plugin/monitoring-fm-plugin-ca.pem"
        - name: FM_MONITORING_PLUGIN_PUBLIC_KEY
          value: "/opt/axway/FlowManager/monitoring-fm-plugin/monitoring-fm-plugin-public-key.pem"
        - name: FM_MONITORING_PLUGIN_DISABLED
          value: "true"
        - name: FM_JVM_XMX
          value: "2G"
        - name: FM_JVM_XMS
          value: "512M"
        - name: FM_JVM_XMN
          value: "768M"
        - name: FM_UNMANAGED_PRODUCT_ENABLED
          value: "false"
      volumeMounts:
        - mountPath: /opt/axway/FlowManager/configs
          name: configs
        - mountPath: /opt/axway/FlowManager/conf/license
          name: license
        - mountPath: /opt/axway/FlowManager/conf/schemas/storage
          name: plugins
        - mountPath: /opt/axway/FlowManager/updates
          name: updates
        - mountPath: /opt/axway/logs
          name: logs
        - mountPath: /opt/axway/FlowManager/init
          name: initialize
        - mountPath: /opt/axway/FlowManager/st-fm-plugin
          name: st-fm-plugin
        - mountPath: /opt/axway/FlowManager/monitoring-fm-plugin
          name: monitoring-fm-plugin

    - image: docker.repository.axway.com/flowmanager-stplugin-docker-prod/2.0/st-fm-plugin:2.0.20230728
      name: st-fm-plugin
      ports:
        - name: stport
          hostPort: 8899
          containerPort: 8899
          protocol: tcp
      env:
        - name: ST_FM_PLUGIN_HOST
          value: "flowmanager_pod-st-fm-plugin"
        - name: ST_FM_PLUGIN_PORT
          value: "8899"
        - name: ST_FM_PLUGIN_SHORT_NAME
          value: "ST"
        - name: ST_FM_PLUGIN_FM_FQDN     # FQDN of the machine
          value: ""
        - name: ST_FM_PLUGIN_FM_PORT
          value: "8081"
        - name: ST_FM_PLUGIN_SHARED_SECRET
          value: "/usr/src/app/src/st-fm-plugin-shared-secret"
        - name: ST_FM_PLUGIN_FM_GOV_CA_FULL_CHAIN
          value: "/usr/src/app/src/governanceca.pem"
        - name: ST_FM_PLUGIN_SERVER_PRIVATE_KEY_PEM
          value: "/usr/src/app/src/st-fm-plugin-cert-key.pem"
        - name: ST_FM_PLUGIN_CERT_PEM
          value: "/usr/src/app/src/st-fm-plugin-cert.pem"  
        - name: ST_FM_PLUGIN_SERVER_CA_FULL_CHAIN
          value: "/usr/src/app/src/st-fm-plugin-ca.pem"
        - name: ST_FM_PLUGIN_JWT_KEY
          value: "/usr/src/app/src/st-fm-plugin-private-key.pem"
        - name: ST_FM_PLUGIN_DATABASE_ENDPOINTS
          value: "flowmanager_pod-mongodb:27017"
        - name: ST_FM_PLUGIN_DATABASE_NAME
          value: "umcft"
        - name: ST_FM_PLUGIN_DATABASE_USER_NAME
          value: ""
        - name: ST_FM_PLUGIN_DATABASE_USER_PASSWORD
          value: ""
        - name: ST_FM_PLUGIN_DATABASE_CONNECTION_RETRIES
          value: "15"
        - name: ST_FM_PLUGIN_DATABASE_CONNECTION_RETRY_INTERVAL
          value: "60"
        - name: ST_FM_PLUGIN_DATABASE_USE_SSL
          value: "false"
        - name: ST_FM_PLUGIN_DATABASE_CERTIFICATES
          value: ""  
      volumeMounts:
        - mountPath: /usr/src/app/src
          name: st-fm-plugin  

    - image: docker.repository.axway.com/flowmanager-monitoringplugin-docker-prod/2.0/monitoring-fm-plugin:2.0.20230728
      name: monitoring-fm-plugin
      ports:
        - name: monitoringport
          hostPort: 3000
          containerPort: 3000
          protocol: tcp
      env:
        - name: MONITORING_PLUGIN_HOST
          value: "flowmanager_pod-monitoring-fm-plugin"
        - name: MONITORING_PLUGIN_PORT
          value: "3000"
        - name: MONITORING_PLUGIN_SHORT_NAME
          value: "MON"
        - name: MONITORING_PLUGIN_FM_HOST     # host of the machine
          value: ""
        - name: MONITORING_PLUGIN_FM_PORT
          value: "8081"
        - name: MONITORING_PLUGIN_SHARED_SECRET
          value: ""
        - name: MONITORING_PLUGIN_TRUSTSTORE
          value: "governanceca.pem"
        - name: MONITORING_PLUGIN_PRIVATE_KEY_PEM
          value: "monitoring-fm-plugin-cert-key.pem"
        - name: MONITORING_PLUGIN_CERT_PEM
          value: "monitoring-fm-plugin-cert.pem"  
        - name: MONITORING_PLUGIN_CA_CHAIN
          value: "monitoring-fm-plugin-ca.pem"
        - name: MONITORING_PLUGIN_JWT_KEY
          value: "monitoring-fm-plugin-private-key.pem"
        - name: MONITORING_PLUGIN_DB_ENDPOINTS
          value: "flowmanager_pod-mongodb:27017"
        - name: MONITORING_PLUGIN_DB_NAME
          value: "umcft"
        - name: MONITORING_PLUGIN_DB_USER_NAME
          value: ""
        - name: MONITORING_PLUGIN_DB_USER_PASSWORD
          value: ""
        - name: MONITORING_PLUGIN_DB_USE_SSL
          value: "false"
        - name: MONITORING_PLUGIN_DB_CERTIFICATES
          value: ""
      volumeMounts:
        - mountPath: /usr/src/app/conf
          name: monitoring-fm-plugin

  volumes:
    - hostPath:
        path: ./files/mongo/scripts
        type: Directory
      name: scripts
    - hostPath:
        path: ./files/mongo/config
        type: Directory
      name: config
    - hostPath:
        path: ./mongodb_data_container
        type: Directory
      name: data
    - hostPath:
        path: ./files/flowmanager/configs
        type: Directory
      name: configs
    - hostPath:
        path: ./files/flowmanager/license
        type: Directory
      name: license
    - hostPath:
        path: ./files/flowmanager/plugins
        type: Directory
      name: plugins
    - hostPath:
        path: ./files/flowmanager/updates
        type: Directory
      name: updates
    - hostPath:
        path: ./files/flowmanager/logs
        type: Directory
      name: logs
    - hostPath:
        path: ./files/flowmanager/initialize
        type: Directory
      name: initialize
    - hostPath:
        path: ./files/st-fm-plugin
        type: Directory
      name: st-fm-plugin
    - hostPath:
        path: ./files/monitoring-fm-plugin
        type: Directory
      name: monitoring-fm-plugin
