##
## Default values for Monitoring PLUGIN deployment
##
## Image and version of Monitoring PLUGIN
image:
  repository: docker.repository.axway.com/flowmanager-monitoringplugin-docker-prod/2.0/monitoring-plugin
  tag: "2.0.20221005"

## Replica/Number of containers
replicaCount: 1

## Deployment type
deployment:
  strategy:
    rollingUpdateType: RollingUpdate
    maxUnavailable: 1
    maxSurge: 0

podAnnotations: {}

## Container command
containerCommandDisabled: true
container:
  ports:
    - name: monitoring-plugin-http
      internalPort: 3000

## Node selector
nodeSelectorDisabled: true
tolerationsDisabled: true

## Environment variables
envFromValueDisabled: true
envFromConfigMapRefDisabled: true
envFromSecretKeyRefDisabled: true

## Readiness
readinessProbeDisabled: true
## Resources
resourcesDisabled: true
resources:
  requests:
    cpu: 256m
    memory: 1Gi
    ephemeralStorage: 2Gi
  limits:
    cpu: 512m
    memory: 2Gi
    ephemeralStorage: 2Gi

## Service
service:
  type: ClusterIP
  ports:
    - name: monitoring-plugin-http
      internalPort: 3000
     #externalPort: 8899
     
tls: false
ingress:
  enabled: false