---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  selector:
    app: {{ template "fullname" . }}
    app.kubernetes.io/instance: {{ template "fullname" . }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .externalPort }}
    targetPort: {{ .internalPort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  type: {{ .Values.service.type | quote }}
