##
## Flow Manager Core deployment
##
core:
  replicaCount: 2

  ## Docker image used for the customer
  image:
    repository: axway/flowmanager
    tag: 2.0.200709

  podAnnotations: {}
    #sidecar.istio.io/inject: "false"

  ## Environment variables
  envFromConfigMapDisabled: true
  envFromValueDisabled: false
  env:
    variables:
      ACCEPT_EULA: "no"
   
  ## Volumes
  volumesSecretDisabled: false
  volumesMountsSecretDisabled: false
  
  ## Resources specification
  resources:
    requests:
      cpu: "2000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "4Gi"
  ## Service
  service:
    type: ClusterIP # or LoadBalancer
    annotations: {}
    externalPort: 8081
  ##
  ## Security parameters
  ##
  serviceAccount:
    create: false
    # name: ~

  rbac:
    create: false

  pspEnable: false

  podAnnotations: {}

  containerSecurityContext:
    {}
    # privileged: false
    # allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: false
    # capabilities:
    #   drop:
    #     - ALL


  ## Configure readiness and liveness for health check
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /fm/login
      port: 443
      scheme: HTTPS
    initialDelaySeconds: 100
    periodSeconds: 5
    successThreshold: 3

  livenessProbe:
    httpGet:
      path: /api/v2/internals/stability
      port: 443
      scheme: HTTPS
    initialDelaySeconds: 100
    successThreshold: 1
    failureThreshold: 2
    periodSeconds: 10

  ## Setup ingress for Flow Manager Core
  ingress:
    enabled: false
    #annotations:
    #  nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    #  ingress.kubernetes.io/secure-upstream: "true"
    #  kubernetes.io/ingress.class: "nginx"
    #  kubernetes.io/tls-acme: "true"
    #secretName: tls
    #tls:
    #  - hosts:
    #      - flowmanager.mydomain.com
    #    secretName: tls
    #hosts:
    #  - host: flowmanager.mydomain.com
    #    paths: [/]          
##
## ST Plugin deployment
##
st-plugin:
  ##
  ## Default values for ST FM PLUGIN deployment
  ##
  ## Image and version of ST FM PLUGIN
  image:
    repository: axway/st-fm-plugin
    tag: "2.0.20210730"

  ## Replica/Number of containers
  replicaCount: 1

  ## Deployment type
  deployment:
    strategy:
      rollingUpdateType: RollingUpdate
      maxUnavailable: 1
      maxSurge: 0
  
  podAnnotations: {}
    #sidecar.istio.io/inject: "false"

  ## Container command
  containerCommandDisabled: true
  container:
    ports:
      - name: st-plugin-http
        internalPort: 8899

  ## Node selector
  nodeSelectorDisabled: true
  tolerationsDisabled: true

  ## Environment variables
  envFromConfigMapDisabled: true
  envFromValueDisabled: false
  env:
    variables:
      ST_FM_PLUGIN_PORT: 8899
      ST_FM_PLUGIN_SHORT_NAME: "ST"

  ## Readiness
  readinessProbeDisabled: true
  ## Resources
  resourcesDisabled: true
  resources:
    requests:
      cpu: 256m
      memory: 1Gi
      ephemeralStorage: 2Gi
    limits:
      cpu: 512m
      memory: 2Gi
      ephemeralStorage: 2Gi

  ## Volumes
  volumesSecretDisabled: false
  volumesMountsSecretDisabled: false
    
  ## Service
  service:
    type: ClusterIP
    ports:
      - name: st-plugin-http
        internalPort: 8899
       #externalPort: 8899
       
  ## Ingress
  tls: false
  ingress:
    enabled: false   